rss_feeds:
  engineering:
    # Software Engineering & Architecture
    - name: "Example Engineering Blog"
      url: "https://example.com/engineering/feed"
    - name: "Example Architecture Blog"
      url: "https://example.com/architecture/feed"

  data_analytics:
    - name: "Example Data Blog"
      url: "https://example.com/data/feed"
    - name: "Example Analytics Blog"
      url: "https://example.com/analytics/feed"

  management:
    - name: "Example Management Blog"
      url: "https://example.com/management/feed"
    - name: "Example Leadership Blog"
      url: "https://example.com/leadership/feed"

settings:
  log_file: rss_bot.log
  db_path: /home/ec2-user/rss-discord-bot/rss_bot.db
  seen_entries_file: "seen_entries.json"
  channels:
    engineering:
      id: "YOUR_ENGINEERING_CHANNEL_ID"
    data_analytics:
      id: "YOUR_DATA_ANALYTICS_CHANNEL_ID"
    management:
      id: "YOUR_MANAGEMENT_CHANNEL_ID" 